package com.samharrison.payments.reconciliation.internal;

enum SettlementFileErrorCode {
    EMPTY_FILE,
    FILE_TOO_LARGE,
    UTF8_BOM_NOT_ALLOWED,
    MALFORMED_UTF8,
    NUL_CHARACTER,
    INVALID_CSV,
    INVALID_HEADER,
    INVALID_COLUMN_COUNT,
    EMPTY_DATA,
    TOO_MANY_ROWS,
    CONTROL_CHARACTER,
    INVALID_SETTLEMENT_RECORD_ID,
    DUPLICATE_SETTLEMENT_RECORD_ID,
    INVALID_PAYMENT_ID,
    INVALID_AMOUNT,
    INVALID_CURRENCY,
    INVALID_SETTLED_AT
}
